[pytest]
testpaths = testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -ra --strict-markers
log_cli = true
log_cli_level = INFO
markers =
    login: login workflow tests
    au_pro: AU PRO feature tests
    smoke: smoke tests
